Novo teste de Frontend
hashlab/hiring pull request #18
Opened 2020-01-06 18:23 UTC by paulovitin

2020-01-07 15:32 UTC, lucasveigaf commented on challenges/pt-br/front-challenge.md
> +- Componentize todos os elementos
Acho esse requisito um pouco complicado... No fim das contas, dá pra componentizar a nível bem macro quanto super micro. O que `Todos` significa vai variar de candidato pra candidato.

Sendo assim, e como o interessante é ver como o candidato pensa componentização, eu deixaria apenas algo como `Se preocupe com componentização` ou algo nessa linha.

2020-01-07 15:37 UTC, lucasveigaf commented
Gostei da nova versão 👏 🚀 

A anterior também era boa, mas me parece que essa dá mais foco pra cenários mais reais.

2020-01-07 15:47 UTC, paulovitin commented on challenges/pt-br/front-challenge.md
> +- Componentize todos os elementos
@lucasveigaf feito

2020-01-07 15:49 UTC, lucasveigaf approved these changes

2020-01-07 23:19 UTC, heyvito requested changes

2020-01-07 23:19 UTC, heyvito commented on challenges/pt-br/front-challenge.md
> +O objetivo do desafio é validar seus conhecimentos em JavaScript, então aproveite o desafio para mostrar tudo o que você sabe sobre as novas features da linguagem, TypeScript(caso opte, mostre todo o
Acho que ficou meio estranho.

```suggestion
O objetivo do desafio é validar seus conhecimentos nos seguintes tópicos:
- **JavaScript**: aproveite o desafio para mostrar tudo o que sabe sobre as novas features da linguagem.
- **TypeScript**: Opcional. Caso opte por usá-lo, mostre todo o seu domínio. 
- **Componentização** 
- **Processadores de CSS**: seja IN-JS ou demais
-  **Testes unitários** 
- **Testes end-to-end**
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +Vamos analisar o seu teste com base no que foi dito acima, então, dê um show pra gente ficar impressionado.
```suggestion
Analisaremos seu teste com base nos critérios acima, então dê um show para que fiquemos impressionados.
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +2.  **São permitidas** ferramentas modernas de desenvolvimento como TypeScript, Babel, eslint, webpack, assim como o uso de polyfills (e outras ferramentas para melhorar o suporte a browsers, como o
```suggestion
2.  **São permitidas** ferramentas modernas de desenvolvimento como TypeScript, Babel, eslint, webpack, assim como o uso de polyfills (e outras ferramentas para melhorar o suporte a browsers, como Modernizr) e/ou bibliotecas para testes.
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +1.  **Não é permitido** utilizar frameworks e/ou bibliotecas de UI, como React, Vue.js, Angular e JSX (queremos ver a sua habilidade com JS e DOM).
```suggestion
1.  **Não é permitido** utilizar frameworks e/ou bibliotecas de UI, como React, Vue.js, Angular e JSX (queremos ver sua habilidade com JS e DOM).
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
>  3. Você demonstra conhecimento de como testar as partes críticas do aplicativo. **Não exigimos** 100% de cobertura.
Nota: Até agora é citado como "a aplicação", e aqui muda para "o aplicativo"

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +Hoje nossos clientes precisam saber quanto custa antecipar uma transação, e para isso, precisamos desenvolver uma calculadora de antecipação para que os mesmos consigam saber quais valores eles vão r
```suggestion
Hoje nossos clientes precisam saber quanto custa antecipar uma transação, e para isso, precisamos desenvolver uma calculadora de antecipação para que os mesmos consigam saber quais valores receberão caso optem por antecipar o recebimento.
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +- Faça testes unitários e/ou de ponta-a-ponta (end-to-end)
Isso já foi citado anteriormente. A repetição é intencional?

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +- Os possíveis cenários devem ser cobertos e terem suas soluções implementadas. Não foi desenvolvido layout para isso, pois queremos observar como você vai lidar com esses cenários:
Isso fica um pouco confuso no meio da lista. Que tal transformarmos num paragráfo?

```suggestion

Os possíveis cenários devem ser cobertos e terem soluções implementadas. Não foi desenvolvido layout para isso, pois queremos observar como você lidará com eles:
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +Você irá consumir uma api já existente. Segue as especifiações da API:
```suggestion
Você consumirá uma API já existente no endereço abaixo. Em seguida há uma especificação simplificada dela.
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +`http://hash-front-test.herokuapp.com/`
Isso não deveria ser HTTPS?

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +| Parâmetro    | Required | Tipo          | Descrição                                                                              |
```suggestion
| Parâmetro    | Obrigatório? | Tipo          | Descrição                                                                              |
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +| amount       | Sim      | number        | Valor total da transação em centavos                                                   |
```suggestion
| `amount`       | Sim      | `number`        | Valor total da transação em centavos                                                   |
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +| installments | Sim      | number        | Número de parcelas                                                                     |
```suggestion
| `installments` | Sim      | `number`        | Número de parcelas                                                                     |
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +| mdr          | Sim      | number        | É a taxa cobrada pelas adquirentes sobre cada transação de cartão de crédito ou débito |
```suggestion
| `mdr`          | Sim      | `number`        | É a taxa cobrada pelas adquirentes sobre cada transação de cartão de crédito ou débito |
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +| days         | Não      | Array<number> | Uma lista com os dias a serem calculadas as antecipações                               |
Achei a descrição desse item confusa. Talvez um rewording melhore-a.

```suggestion
| `days`         | Não      | `Array<number>` | Uma lista com os dias a serem calculadas as antecipações                               |
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +{"1":13267,"15":13536,"30":13824,"90":14400}%
```suggestion
{"1":13267,"15":13536,"30":13824,"90":14400}
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +{"30":13824,"60":14208,"90":14400}%
```suggestion
{"30":13824,"60":14208,"90":14400}
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +Para **Timeout** basta executar a request post passando `timeout` como query string, exemplo:
```suggestion
Para **Timeout** basta executar a request post passando `timeout` através da query string, exemplo:
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +Para **Internal Server Error** basta executar a request post passando `timeout` como query string, exemplo:
```suggestion
Para **Internal Server Error** basta executar a request post passando `internalError` através da query string, exemplo:
```

2020-01-07 23:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +Para **Delay de resposta**, que pode ser usado como simulador de conexão lenta, basta executar a request post passando `delay` informando o tempo do delay em milissegundos, exemplo:
```suggestion
Para **Delay de resposta**, que pode ser usado como simulador de conexão lenta, basta executar a request post passando `delay`, e informando o tempo do delay em milissegundos, exemplo:
```

2020-01-07 23:23 UTC, victorgama commented
@paulovitin As sugestões acima são _bem_ particulares por conta do meu ódio por artigos e pronomes que podem ser suprimidos. :P
Também adicionei umas formatação extra na sua tabela, e corrigi umas inconsistências que encontrei no fim do arquivo.

2020-01-08 15:24 UTC, paulovitin commented on challenges/pt-br/front-challenge.md
> +- Faça testes unitários e/ou de ponta-a-ponta (end-to-end)
É so para reforçar que vamos avaliar isso e que é obrigatório ter.

2020-01-08 19:14 UTC, paulovitin commented
> @paulovitin As sugestões acima são _bem_ particulares por conta do meu ódio por artigos e pronomes que podem ser suprimidos. :P
> Também adicionei umas formatação extra na sua tabela, e corrigi umas inconsistências que encontrei no fim do arquivo.

@victorgama sem problemas. Alterações feitas ;)

2020-01-08 19:18 UTC, heyvito requested changes

2020-01-08 19:18 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +7. Segue algum guia de estilo de código padronizado
Só para não quebrar o padrão das outras linhas:

```suggestion
7. Segue algum guia de estilo de código padronizado.
```

2020-01-08 19:19 UTC, victorgama commented on challenges/pt-br/front-challenge.md
> +- Faça testes unitários e/ou de ponta-a-ponta (end-to-end)
Show! Obg @paulovitin! ❤️

2020-01-08 19:19 UTC, heyvito approved these changes
LGTM! ✅

2020-01-08 19:26 UTC, merged