Add frontend-challenge.md
hashlab/hiring pull request #9
Opened 2019-08-22 20:09 UTC by paulovitin

### Considerations:
- The layout is not completely defined yet.

2019-08-22 21:13 UTC, pcstl commented on challenges/pt-br/front-challenge.md
> + 2. É permitido ferramentas modernas de desenvolvimento como TypeScript, Babel, eslint, webpack, usar polyfills ou bibliotecas para testes.
```suggestion
 2. São permitidas ferramentas modernas de desenvolvimento como TypeScript, Babel, eslint, webpack, assim como o uso de polyfills (e outras ferramentas para melhorar o suporte a browsers, como o Modernizr) e/ou bibliotecas para testes.
```

2019-08-22 21:15 UTC, pcstl commented on challenges/pt-br/front-challenge.md
> + 1. Não é permitido utilizar frameworks, como React, Vue.js, Angular.
Eu acho que precisamos ser mais específicos sobre o que definimos como "Framework". O próprio React, embora muitos chamem de "framework", se define como "uma biblioteca de UI", não um framework, ao contrário do Vue e do Angular.

Eu entendo que a intenção aqui é que o site tem que ser escrito em Vanilla JavaScript, ao invés de usar uma biblioteca que gerencia o DOM pra você, mas acho que é uma boa deixar isso explícito.

2019-08-22 21:15 UTC, pcstl commented on challenges/pt-br/front-challenge.md
> + 3. É permitido pré processadores de CSS ou CSS-in-JS
```suggestion
 3. São permitidos pré-processadores de CSS ou bibliotecas CSS-in-JS.
```

2019-08-22 21:16 UTC, pcstl commented on challenges/pt-br/front-challenge.md
> +1. Conversaremos sobre a estrutura do código, a forma como o projeto foi organizado, e outras decisões que foram tomadas
```suggestion
1. Conversaremos sobre a estrutura do código, a forma como o projeto foi organizado, e outras decisões que foram tomadas.
```

2019-08-22 21:16 UTC, pcstl commented on challenges/pt-br/front-challenge.md
> +2. Discutiremos como esse sistema evoluiria ao longo do tempo
```suggestion
2. Discutiremos como esse sistema evoluiria ao longo do tempo.
```

2019-08-22 21:16 UTC, pcstl commented on challenges/pt-br/front-challenge.md
> +3. Considere que mais pessoas irão trabalhar junto com você nesse projeto
```suggestion
3. Considere que mais pessoas irão trabalhar junto com você nesse projeto.
```

2019-08-22 21:18 UTC, pcstl commented on challenges/pt-br/front-challenge.md
> +[Link para o layout](https://zpl.io/ameEPBe)
Eu tentei abrir o layout e deu "Você não foi convidado para este projeto". Acho que tem que deixar público. Não sei se é intencional e só vai ficar público quando estiver pronto.

2019-08-22 21:19 UTC, pcstl commented on challenges/pt-br/front-challenge.md
> +- A data de recebimento devem ser fixas nos seguintes periodos: (como apresentado no layout)
```suggestion
- A data de recebimento deve ser fixada nos seguintes periodos: (como apresentado no layout)
```

2019-08-22 21:19 UTC, pcstl commented on challenges/pt-br/front-challenge.md
> +- Mantenha o layout pixel by pixel como proposto no link
```suggestion
- Mantenha o layout pixel by pixel conforme proposto no link
```

2019-08-22 21:20 UTC, coproduto requested changes
Sugeri algumas alterações

2019-08-23 13:36 UTC, paulovitin commented on challenges/pt-br/front-challenge.md
> +[Link para o layout](https://zpl.io/ameEPBe)
Era para estar público. Vou mexer nisso hahaha

2019-08-23 13:42 UTC, paulovitin commented on challenges/pt-br/front-challenge.md
> + 1. Não é permitido utilizar frameworks, como React, Vue.js, Angular.
Alterado.

2019-08-23 18:03 UTC, MarcoWorms approved these changes

2019-08-26 16:24 UTC, felipeblassioli approved these changes

2019-08-26 16:28 UTC, ocaio approved these changes

2019-08-26 16:40 UTC, kpilon approved these changes

2019-08-26 16:49 UTC, merged